blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/TakosThings/Fluent-Discord/wiki
    about: Visit the wiki for information on getting started with the theme.
